### PR TITLE
hi there i  have updated the whole calculator file

### PR DESCRIPTION
**Pull request by Shubham56-droid**
1. I have changed its UI to an awesome glassmorphisms effect as well as changes the size and texture of the button and display.
2. I have made your project fully responsive to phone and pc.
3. I  have added a preloader to your website.
4. I have added an images folder to hold images on the website and also added an updated screenshot folder as u mention in contribute.MD rules to add before and after screenshot
5. Hope u like , If u like it pls merge my pull request

### CODE REVIEW

**Comment by Shubham56-droid** [comment]
hi bro pls accept my pr

**Comment by Shubham56-droid** [comment]
u have just closed the issue pls check my  pr

**Comment by mohdsauood** [comment]
Hi @Shubham56-droid ! The ui looks great , nice work ! but the buttons alignment breaks when width breakpoint is above 1800px . [ui-issue.png](https://imgur.com/QBwecAv)

Can you please do these below changes and send a pr again ? 
1) fix the buttons alignments above 1800px width
2) remove the update screenshots folder

In the above pr description , you have mentioned 5 points . i want the link of before and after images among the 5 points, not in the project's code . 

Let me know if you could work on it or i'd merge the code and assign these tasks to someone else .

Thank you for your contribution .

**Comment by Shubham56-droid** [comment]
Ok sure it will do it

**Comment by Shubham56-droid** [comment]
I have done all the customisation as u have asked for pls do check my pr #6

**Pull request merged**
